import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitest/config'

const sourceCondition = '@systemfsoftware/source'
const excluded = ['**/.stryker-tmp/**', '**/node_modules/**']
const unguarded = [
  'src/graph/test/adjacency.test.ts',
  'src/graph/test/dieHard.test.ts',
  'src/graph/test/graph.test.ts',
  'src/graph/test/index.test.ts',
  'src/graph/test/paths.test.ts',
  'src/graph/test/shortestPaths.test.ts',
  'src/graph/test/traversal-regressions.test.ts',
  'src/graph/types.test.ts',
  'test/actions.test.ts',
  'test/activities.test.ts',
  'test/actor.test.ts',
  'test/actorLogic.test.ts',
  'test/addressFirstIdentity.test.ts',
  'test/after.test.ts',
  'test/assign.test.ts',
  'test/asyncErrorSchema.types.test.ts',
  'test/asyncTransition.test.ts',
  'test/childCompletionEvents.types.test.ts',
  'test/choice.test.ts',
  'test/clock.test.ts',
  'test/conversion.test.ts',
  'test/createActor.test.ts',
  'test/createInvoke.test.ts',
  'test/custom-interpreter.test.ts',
  'test/deep.test.ts',
  'test/delayNames.types.test.ts',
  'test/deterministic.test.ts',
  'test/durable-adapters/inngest.test.ts',
  'test/durable-adapters/rivet.test.ts',
  'test/durable-address-first.test.ts',
  'test/durable-adoption.test.ts',
  'test/durable-event-journal-timers.test.ts',
  'test/durable-execution-identity.test.ts',
  'test/durable-execution.test.ts',
  'test/durable-inspection.test.ts',
  'test/durable-interpreter.test.ts',
  'test/durable-reference-host.test.ts',
  'test/durable-restore.test.ts',
  'test/emit.test.ts',
  'test/errorPrecedence.test.ts',
  'test/errors.test.ts',
  'test/event.test.ts',
  'test/eventBoundary.test.ts',
  'test/eventDescriptors.test.ts',
  'test/eventDescriptors.types.test.ts',
  'test/examples.6.16.test.ts',
  'test/examples.6.17.test.ts',
  'test/examples.6.6.test.ts',
  'test/examples.6.8.test.ts',
  'test/examples.6.9.test.ts',
  'test/examples.cd.test.ts',
  'test/final.test.ts',
  'test/firstTenMinutes.v6.test.ts',
  'test/fsm-entrypoint.test.ts',
  'test/fsm.actor.test.ts',
  'test/fsm.differential.test.ts',
  'test/fsm.setup.test.ts',
  'test/fsm.test.ts',
  'test/fsm.types.test.ts',
  'test/guards.test.ts',
  'test/history.test.ts',
  'test/id.test.ts',
  'test/initial.test.ts',
  'test/input.test.ts',
  'test/inspect.test.ts',
  'test/inspection.conformance.v6.test.ts',
  'test/internalEvents.test.ts',
  'test/internalTransitions.test.ts',
  'test/interpreter.test.ts',
  'test/invalid.test.ts',
  'test/invoke.test.ts',
  'test/issue5454.test.ts',
  'test/issueRegressions.test.ts',
  'test/issueRegressions.types.test.ts',
  'test/json.test.ts',
  'test/listen.test.ts',
  'test/logger.test.ts',
  'test/logical-timers.test.ts',
  'test/machine.test.ts',
  'test/machineFromConfig.test.ts',
  'test/machineOutput.types.test.ts',
  'test/machineVersions.test.ts',
  'test/machineVersions.types.test.ts',
  'test/macrostepBound.test.ts',
  'test/memory.test.ts',
  'test/meta.test.ts',
  'test/microstep.test.ts',
  'test/microstep.v6.test.ts',
  'test/multiple.test.ts',
  'test/multiple.v6.test.ts',
  'test/order.test.ts',
  'test/parallel.test.ts',
  'test/parallelConformance.test.ts',
  'test/persistedSnapshot.types.test.ts',
  'test/persistenceConformance.v6.test.ts',
  'test/predictableExec.test.ts',
  'test/rehydration.test.ts',
  'test/rehydration.v6.test.ts',
  'test/resolve.test.ts',
  'test/resolve.v6.test.ts',
  'test/restoreEventless.test.ts',
  'test/restoreTerminal.test.ts',
  'test/restored-effects.test.ts',
  'test/route.test.ts',
  'test/runtimeValidation.test.ts',
  'test/runtimeValidation.types.test.ts',
  'test/select.test.ts',
  'test/serialization.conformance.v6.test.ts',
  'test/setup.test.ts',
  'test/setupStateContracts.test.ts',
  'test/sourceTyping.types.test.ts',
  'test/spawn.test.ts',
  'test/spawn.types.test.ts',
  'test/spawnChild.test.ts',
  'test/state.test.ts',
  'test/stateIn.test.ts',
  'test/stateInput.persistence.test.ts',
  'test/stateInput.test.ts',
  'test/strictTargets.types.test.ts',
  'test/system.test.ts',
  'test/systemOnRejectedEvent.test.ts',
  'test/systemTransition.test.ts',
  'test/tags.test.ts',
  'test/timeout.test.ts',
  'test/timers.persistence.test.ts',
  'test/toPromise.test.ts',
  'test/transient.test.ts',
  'test/transition.test.ts',
  'test/transitionFunctions.test.ts',
  'test/trigger.test.ts',
  'test/typeHelpers.test.ts',
  'test/typeSchemas.test.ts',
  'test/typeStates.test.ts',
  'test/types.test.ts',
  'test/unhandledEvents.test.ts',
  'test/v5ConfigDiagnostics.test.ts',
  'test/v6.test.ts',
  'test/versioning.test.ts',
  'test/vizTypeFriction.types.test.ts',
  'test/waitFor.test.ts',
]

const ownSource = (module: string): string => fileURLToPath(new URL(`./src/${module}`, import.meta.url))

export default defineConfig({
  resolve: {
    alias: [
      { find: /^@systemfsoftware\/xstate$/, replacement: ownSource('index.ts') },
      { find: /^@systemfsoftware\/xstate\/actors$/, replacement: ownSource('actors/index.ts') },
      { find: /^@systemfsoftware\/xstate\/durable$/, replacement: ownSource('durable/index.ts') },
      { find: /^@systemfsoftware\/xstate\/fsm$/, replacement: ownSource('fsm/index.ts') },
      { find: /^@systemfsoftware\/xstate\/graph$/, replacement: ownSource('graph/index.ts') },
      { find: /^@systemfsoftware\/xstate\/validation$/, replacement: ownSource('validation/index.ts') },
    ],
    conditions: ['module', 'browser', 'development|production', sourceCondition],
  },
  ssr: { resolve: { conditions: ['module', 'node', 'development|production', sourceCondition] } },
  test: {
    globals: false,
    environment: 'node',
    exclude: excluded,
    passWithNoTests: true,
    projects: [
      { extends: true, test: { name: 'unguarded', globals: true, include: unguarded } },
      {
        extends: true,
        test: {
          name: 'own',
          setupFiles: ['@systemfsoftware/vitest/guard'],
          include: ['src/**/*.test.{ts,tsx}', 'tests/**/*.test.{ts,tsx}', 'test/**/*.test.{ts,tsx}'],
          exclude: [...excluded, ...unguarded],
        },
      },
    ],
  },
})
